config/routes.rb
Rails.application.routes.draw do

  root 'acronyms#index'

  resources :acronyms, only: [:index, :show]

  get '/search', to: 'acronyms#search', as: 'search'

end

app/models/acronym.rb
class Acronym < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :definition, presence: true
end

app/controllers/acronyms_controller.rb
class AcronymsController < ApplicationController
  def index
    @acronyms = Acronym.all.order(Arel.sql("lower(name)"))
  end

  def show
    @acronym = Acronym.find(params[:id])
  end

  def search
    term = "%" + params[:query].downcase + "%"
    @acronyms = Acronym.where("lower(name) LIKE ?", term)
    @definitions = Acronym.where("lower(definition) LIKE ?", term)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acronyms/_acronym.html.erb
<p class="definition"><%= link_to acronym.name, acronym_path(acronym) %> - <%= acronym.definition %></p>

app/views/acronyms/index.html.erb
<h2>Acronyms</h2>

<%= render partial: "acronym", collection: @acronyms %>

app/views/acronyms/search.html.erb
<h3>Search Results - Acronyms</h3>

<%= render partial: "acronym", collection: @acronyms %>

<h3>Search Results - Definitions</h3>

<%= render partial: "acronym", collection: @definitions %>

app/views/acronyms/show.html.erb
<h2><%= @acronym.name %></h2>

<p><%= @acronym.definition %></p>
<p><%= @acronym.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IT Acronyms</title>
    <link href='https://fonts.googleapis.com/css?family=Jura|Open+Sans' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <div id="header">
        <h1 id="title"><%= link_to "IT Acronyms", acronyms_path %></h1>
        <nav>
          <ul>
            <li>
              <%= form_tag("/search", method: "get") do %>
                <%= text_field_tag :query %>
                <%= submit_tag("Search") %>
              <% end %>
            </li>
          </ul>
        </nav>
      </div>

      <div id="content">
        <%= yield %>
      </div>
  </body>
</html>